apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private-k8s
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/ksefuke-labs/kubernetes-homelab-priv
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-k8s
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age