apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf-cert
  namespace: audiobookshelf
spec:
  # Secret names are always required.
  secretName: abs-cert-secret
   # Issuer references are always required.
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - abs.staging.ksefuke-labs.com
  
 