apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:y2kyRC3KT/ifX4tkLJimwnn/uEXTqavwN97LBU8Xo3he57x+06glUdZvC9IEAxd7rB/8WDp5YpBJLXXI4L2hO++Vz28JC4ti+OAYY38GQWl3/yz/5y4YvNgTsWdNAEgNre1MXp89GIEskZOvtpnxA6JBSg9XvloRfv1fG3OfWF2QmrKfIjokQG8GxM40Frrgr0wxH+94ROmx/EGmkqNHjCtoif4fyDYWGSJR39Xa8RUvhIj1jua8K3cf3qgzCs5V+1yPpLwHqd13vrHbdVa4sKb3GNXoPB3WBESnZITHTsgvrlEd3CdKT6pWock=,iv:AGBuWyOqIcauKKHy5OLHgpDok97yS4zNSLGKF3qZIM4=,tag:dVo59WWbnKLt4pkHw+XxYQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMFFVc05UWE1YTHd1WEx6
            SnhMSnlrYlJoQmJpVDd4aTlTRHltZUp6U0hrCjdkTTYzZ3kzVi91d2xGR0FsRHNr
            UUJUOGYvQWJBR0lGbEwvYXVwSEt6OWcKLS0tIE9hUUs5cExrRHVEdzlqT0oxMlJV
            WFJPbms0SzJ6UFpEQlUvSmRGMEhDQ1UKw+/jobrRqPNdabYzVr65WT6ZlY4yggUm
            /lShL/3j/VvgDaUJeE5vpTmofmptrX9ZOVxfSXgdtOckyjlOFqMHBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:36:22Z"
    mac: ENC[AES256_GCM,data:BPMGozfsZ2EbEQHTQlAoTD/ga5I0dp0p0xj7HQ7j8FftjLcPSV8JNs/TCn8k4aJm5dkEa3Iuka3z+IyC76DVCIxNJ65/SAWswol1Qf61O8QUOrmEVPTX+JGhiOjwUaApIEscOuLAAljudpJzvWQKxVJfCYDBlm1eovC2U66Vmuk=,iv:In2udJ9bdk3C07Y6xPcN6UoIkZ4qLz6jPzi5d5EtqwA=,tag:s/0eX6hweYEiuOMtQJuw6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
