apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name:  infrastructure
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging
  prune: true # FLUX will cleanup resources which have been removed from kustomize file in apps/staging
  
  decryption:
    provider: sops
    secretRef:
      name: sops-age