apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/staging/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system