apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart: cert-manager
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: cert-manager
  version: '1.19.4'
  values:
      crds:
      # This option decides if the CRDs should be installed
      # as part of the Helm installation.
        enabled: true
        # A comma-separated string with the host and port of the recursive nameservers cert-manager should query.
      dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
      # Forces cert-manager to use only the recursive nameservers for verification.
      # Enabling this option could cause the DNS01 self check to take longer owing to caching performed by the recursive nameservers.
      dns01RecursiveNameserversOnly: true
      # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted.
      enableCertificateOwnerRef: false