apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    crds:
      enabled: true
      keep: false
    dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
    dns01RecursiveNameserversOnly: true
    enableCertificateOwnerRef: false