apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-apikey-secret
    namespace: cert-manager
data:
    apikey: ENC[AES256_GCM,data:oTfSnjB5E6xgOrf1PBe61FkiTKWnbQzPKTcrgcD5QcqVPXgRTFOAqWhT4Wve2lZM+skHhtzMAwQ=,iv:lXXYDnui6pH0bTdE2c6+Dus2gUea94AAf+dJRFc1+2s=,tag:oQNKZ+JicyErf/z+jG/ocg==,type:str]
sops:
    age:
        - recipient: age1w0ptdg04h8e6d7nmwjj4unuphwstxrw8fmk9e7jhda28re6c8stqtfcsvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR1lwTG5HS2puTUZPcnJh
            YUVFL0JEY2oxWU5ONzBKUnRLMjhqVTZzSkIwCnBsNnI4czJCOHQ1TzdzNGFVd3I0
            WEFuam9ESlVSRi9mRUxhTXNOVGYwMlUKLS0tIE9BNjM1LzlXdkdweEdIWHVpT3F4
            TTNYMkxKZnFuZUxwRGJsd1EzVnFGekUKgaMVMgme9vM8HEeVLlChQKuej59vtUi8
            x8WGI3qJNs8NpPV47uQrx8u791sb4DrWK5tBt6FgO2ojT6KV+zeXHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T19:54:07Z"
    mac: ENC[AES256_GCM,data:whSWvvsP5q3Cwiu5PSwGexDAa9Wo6KWfQ/qHqiQN0kR5AVUWy79sLNgNDzse5MBruyVT8qCo9SnDcZGLos5RWy9TSXS7+b8PoU5b7K9QnT1REiWgipNPpkT9nKgBu4BY5tDkVjLB1ehans984BR8l720TAP2pfQBlZZuIyUsKro=,iv:Xpfdc8Y8Gz3s1KwVyxrnNtZk8n+XdtThv1/WcwxkGXs=,tag:LN6GsEibxthEepcPu97HkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
