apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 12h
  chart:
    spec:
      chart: traefik
      version: "39.0.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  
  values:
    deployment:
      # -- Enable deployment
      enabled: true
      # -- Deployment or DaemonSet
      kind: Deployment
       # -- Number of pods of the deployment (only applies when kind == Deployment)
      replicas: 1
    
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi

    ports:
        web:
          port: 8000
          exposedPort: 80
          protocol: TCP
          http:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true

        websecure:
          port: 8443
          exposedPort: 443
          protocol: TCP

    providers:
      # Enable Kubernetes CRD provider
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      # Enable Kubernetes Ingress provider
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
    
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.52.100.61

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.staging.internal`)
        entryPoints:
          - web